title: "Learning Pathways"
description: "Get started learning about decentralized trust"
theme: just-the-docs

url: https://trustoverip.github.io/egwg-learning-pathways/

aux_links:
  Template Repository: https://github.com/trustoverip/egwg-learning-pathways

